// flow-typed signature: a28ce177d92cf4cf417e81d01ad33a16
// flow-typed version: <<STUB>>/react-aria-modal_v2.12.3/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-aria-modal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-aria-modal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-aria-modal/dist/react-aria-modal' {
  declare module.exports: any;
}

declare module 'react-aria-modal/src/react-aria-modal' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-aria-modal/dist/react-aria-modal.js' {
  declare module.exports: $Exports<'react-aria-modal/dist/react-aria-modal'>;
}
declare module 'react-aria-modal/src/react-aria-modal.js' {
  declare module.exports: $Exports<'react-aria-modal/src/react-aria-modal'>;
}
