name: Publish-CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: echo ${{github.ref}}
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: yarn clear deps, install and test
      run: |
        yarn run clear:deps
        yarn
        yarn run test
        yarn run build:prod
      env:
        CI: true

  publish:

    runs-on: ubuntu-latest

    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Publish on artifactory
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: configure npm and publish
        run: |
          yarn
          yarn run build:prod
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm config list
          yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}

  release:

    runs-on: ubuntu-latest

    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Release new version
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          draft: false
          prerelease: false
